skip_tags: true
image: Visual Studio 2017
environment:    
  signingkey:
    secure: DcEnjxct82WwrppME28Rkw==

install:
  - cmd: choco install gitversion.portable -pre -y
  #- ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt dazinator.snk.enc -secret %signingkey%

before_build:
  - ps: gitversion /l console /output buildserver

build:
  verbosity: detailed
build_script:
- cmd: dotnet restore ./src/AspNetCore.AuthCookieCompat.sln /p:PackageVersion=%GitVersion_FullSemVer% --disable-parallel
- cmd: dotnet build ./src/AspNetCore.AuthCookieCompat.sln -c Release /p:PackageVersion=%GitVersion_FullSemVer% --disable-parallel
- cmd: dotnet pack ./src/AspNetCore.AuthCookieCompat.sln -c Release /p:PackageVersion=%GitVersion_FullSemVer% --output ../../artifacts/
test_script:
- cmd: dotnet test src/AspNetCore.LegacyAuthCookieCompat.Tests/AspNetCore.LegacyAuthCookieCompat.Tests.csproj
artifacts:
- path: ./artifacts/*
deploy:
  provider: NuGet
  api_key:
    secure: DwF9sQq5V/csRiBuNHKr3a1dBWzJS3GVJBcrKR0ZvePDGcQ47666Jgd6xqU5fvnl
  skip_symbols: false
  artifact: /.*\.nupkg/
